model_name: mymodel_improved
model_dir: ../weight

dataset_path: ../data
embedding_path: ../data/glove.6B.300d.txt

hidden_dim: 256
token_label_dim: 128
num_layers: 1
dropout: 0.2
pretrain: True

batch_size: 128
learning_rate: 0.003
epochs: 30
weight_decay: 4e-5
lr_decay: True

